name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.8
  geocoding: ^4.0.0
  intl: ^0.20.2
  lottie: ^3.1.0
  http: ^1.2.0
  geolocator: ^14.0.2
  shared_preferences: ^2.2.3
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
    uses-material-design: true
    assets:
      - lib/assets/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon.png"
  min_sdk_android: 21
